name: Question
description: Ask for usage help or clarification.
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What have you tried?
